"""Initial clean migration

Revision ID: 770b54a8e10a
Revises: 
Create Date: 2025-11-20 19:51:23.010438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770b54a8e10a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.Enum('COMPANY', 'CARRIER', name='usertype'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('alternative_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('identity_document', sa.String(length=50), nullable=True),
    sa.Column('document_type', sa.Enum('CC', 'NIT', 'RUC', 'CE', 'PASSPORT', name='documenttype'), nullable=True),
    sa.Column('document_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_date', sa.DateTime(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(length=100), nullable=True),
    sa.Column('verification_token_expires', sa.DateTime(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('account_status', sa.Enum('PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'INACTIVE', name='accountstatus'), nullable=True),
    sa.Column('verification_level', sa.Enum('BASIC', 'VERIFIED', 'PREMIUM', name='verificationlevel'), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=True),
    sa.Column('lockout_date', sa.DateTime(), nullable=True),
    sa.Column('accepted_terms', sa.Boolean(), nullable=True),
    sa.Column('terms_acceptance_date', sa.DateTime(), nullable=True),
    sa.Column('notifications_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_user_type'), ['user_type'], unique=False)

    op.create_table('carriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('carrier_type', sa.Enum('INDIVIDUAL', 'COMPANY', name='carriertype'), nullable=False),
    sa.Column('driver_license', sa.String(length=50), nullable=True),
    sa.Column('license_category', sa.String(length=10), nullable=True),
    sa.Column('license_expiry_date', sa.Date(), nullable=True),
    sa.Column('license_issuing_authority', sa.String(length=100), nullable=True),
    sa.Column('active_insurance', sa.Boolean(), nullable=True),
    sa.Column('insurance_policy', sa.String(length=100), nullable=True),
    sa.Column('insurance_expiry_date', sa.Date(), nullable=True),
    sa.Column('insurance_company', sa.String(length=100), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('max_capacity_kg', sa.Float(), nullable=True),
    sa.Column('available_vehicle_types', sa.Text(), nullable=True),
    sa.Column('vehicle_count', sa.Integer(), nullable=True),
    sa.Column('carrier_registration_date', sa.DateTime(), nullable=True),
    sa.Column('completed_trips', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('successful_delivery_rate', sa.Float(), nullable=True),
    sa.Column('total_earnings', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('document_status', sa.Enum('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='documentstatus'), nullable=True),
    sa.Column('documents_complete', sa.Boolean(), nullable=True),
    sa.Column('background_check_verified', sa.Boolean(), nullable=True),
    sa.Column('reliability_seal', sa.Boolean(), nullable=True),
    sa.Column('verification_date', sa.DateTime(), nullable=True),
    sa.Column('cargo_specializations', sa.Text(), nullable=True),
    sa.Column('usual_routes', sa.Text(), nullable=True),
    sa.Column('availability_24_7', sa.Boolean(), nullable=True),
    sa.Column('has_refrigerated_equipment', sa.Boolean(), nullable=True),
    sa.Column('has_dangerous_goods_cert', sa.Boolean(), nullable=True),
    sa.Column('client_reference_1', sa.String(length=200), nullable=True),
    sa.Column('client_reference_2', sa.String(length=200), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_license')
    )
    with op.batch_alter_table('carriers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carriers_user_id'), ['user_id'], unique=True)

    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('commercial_name', sa.String(length=200), nullable=True),
    sa.Column('trade_name', sa.String(length=200), nullable=True),
    sa.Column('incorporation_date', sa.Date(), nullable=True),
    sa.Column('company_type', sa.Enum('NATURAL', 'LEGAL', name='companytype'), nullable=False),
    sa.Column('company_size', sa.Enum('MICRO', 'SMALL', 'MEDIUM', 'LARGE', name='companysize'), nullable=True),
    sa.Column('annual_revenue', sa.Enum('LESS_100K', 'K100_500K', 'K500_1M', 'K1M_5M', 'MORE_5M', name='annualrevenue'), nullable=True),
    sa.Column('direct_employees', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('bank_reference', sa.String(length=100), nullable=True),
    sa.Column('commercial_reference_1', sa.String(length=200), nullable=True),
    sa.Column('commercial_reference_2', sa.String(length=200), nullable=True),
    sa.Column('commercial_reference_3', sa.String(length=200), nullable=True),
    sa.Column('has_environmental_license', sa.Boolean(), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('special_permits', sa.Text(), nullable=True),
    sa.Column('company_registration_date', sa.DateTime(), nullable=True),
    sa.Column('completed_shipments', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('total_spent', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('legal_documentation_complete', sa.Boolean(), nullable=True),
    sa.Column('financial_verification', sa.Boolean(), nullable=True),
    sa.Column('trust_seal', sa.Boolean(), nullable=True),
    sa.Column('verification_date', sa.DateTime(), nullable=True),
    sa.Column('usual_cargo_types', sa.Text(), nullable=True),
    sa.Column('shipping_frequency', sa.Enum('OCCASIONAL', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'DAILY', name='shippingfrequency'), nullable=True),
    sa.Column('coverage_zones', sa.Text(), nullable=True),
    sa.Column('preferred_vehicle_types', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_user_id'), ['user_id'], unique=True)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('USER_ID', 'DRIVER_LICENSE', 'COMPANY_LEGAL', 'VEHICLE_REGISTRATION', 'INSURANCE', 'TAX_DOCUMENT', name='documenttype'), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='documentstatus'), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('PROFILE', 'VEHICLE', 'SHIPMENT', 'DOCUMENT', 'COMPANY', 'GENERAL', name='mediatype'), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('caption', sa.String(length=300), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.Enum('NEW_QUOTE', 'QUOTE_ACCEPTED', 'QUOTE_REJECTED', 'SHIPMENT_UPDATE', 'PAYMENT_RECEIVED', 'NEW_MESSAGE', 'SYSTEM', name='notificationtype'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('read_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cargo_type', sa.Enum('GENERAL_MERCHANDISE', 'FOOD', 'CONSTRUCTION_MATERIALS', 'ELECTRONICS', 'FURNITURE', 'CHEMICALS', 'REFRIGERATED', 'DANGEROUS_GOODS', name='cargotype'), nullable=False),
    sa.Column('origin_address', sa.String(length=300), nullable=False),
    sa.Column('origin_city', sa.String(length=100), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=True),
    sa.Column('origin_lng', sa.Float(), nullable=True),
    sa.Column('destination_address', sa.String(length=300), nullable=False),
    sa.Column('destination_city', sa.String(length=100), nullable=False),
    sa.Column('destination_lat', sa.Float(), nullable=True),
    sa.Column('destination_lng', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('volume_m3', sa.Float(), nullable=True),
    sa.Column('dimensions', sa.String(length=100), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('pickup_date', sa.DateTime(), nullable=False),
    sa.Column('delivery_deadline', sa.DateTime(), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('assigned_date', sa.DateTime(), nullable=True),
    sa.Column('delivered_date', sa.DateTime(), nullable=True),
    sa.Column('offered_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('commission_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PUBLISHED', 'PENDING_QUOTES', 'ASSIGNED', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', 'DISPUTED', name='shipmentstatus'), nullable=True),
    sa.Column('current_location', sa.String(length=200), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.Enum('TRUCK', 'VAN', 'PICKUP', 'TRAILER', 'REFRIGERATED', 'TANKER', name='vehicletype'), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('max_weight_kg', sa.Float(), nullable=False),
    sa.Column('capacity_m3', sa.Float(), nullable=False),
    sa.Column('dimensions', sa.String(length=100), nullable=True),
    sa.Column('has_refrigeration', sa.Boolean(), nullable=True),
    sa.Column('has_hydraulic_tailgate', sa.Boolean(), nullable=True),
    sa.Column('special_features', sa.Text(), nullable=True),
    sa.Column('soat_expiry', sa.Date(), nullable=True),
    sa.Column('technomechanical_expiry', sa.Date(), nullable=True),
    sa.Column('insurance_expiry', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'IN_MAINTENANCE', 'IN_TRANSIT', 'UNAVAILABLE', name='vehiclestatus'), nullable=True),
    sa.Column('current_location', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('last_maintenance_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_plate')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('last_message_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('carrier_payment', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('CREDIT_CARD', 'DEBIT_CARD', 'BANK_TRANSFER', 'PLATFORM_BALANCE', name='paymentmethod'), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REFUNDED', 'CANCELLED', name='paymentstatus'), nullable=True),
    sa.Column('failed_reason', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('processed_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('bid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('counter_offer', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('proposed_pickup_date', sa.DateTime(), nullable=True),
    sa.Column('estimated_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms_conditions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', 'EXPIRED', name='quotestatus'), nullable=True),
    sa.Column('bid_date', sa.DateTime(), nullable=True),
    sa.Column('response_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('punctuality_rating', sa.Integer(), nullable=True),
    sa.Column('communication_rating', sa.Integer(), nullable=True),
    sa.Column('condition_rating', sa.Integer(), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.Column('would_recommend', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id')
    )
    op.create_table('tracking_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('PICKUP', 'DEPARTURE', 'IN_TRANSIT', 'DELAYED', 'ARRIVED', 'DELIVERED', 'CUSTOM', name='trackingeventtype'), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('estimated_remaining_time', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_date', sa.DateTime(), nullable=True),
    sa.Column('sent_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('tracking_events')
    op.drop_table('reviews')
    op.drop_table('quotes')
    op.drop_table('payments')
    op.drop_table('conversations')
    op.drop_table('vehicles')
    op.drop_table('shipments')
    op.drop_table('notifications')
    op.drop_table('media')
    op.drop_table('documents')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_user_id'))

    op.drop_table('companies')
    with op.batch_alter_table('carriers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carriers_user_id'))

    op.drop_table('carriers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_type'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
