"""Fix enum imports for company and carrier

Revision ID: 79c8db98586f
Revises: 3bfa51f43f10
Create Date: 2025-11-12 10:08:10.675507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79c8db98586f'
down_revision = '3bfa51f43f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carriers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documents_complete', sa.Boolean(), nullable=True))
        batch_op.drop_column('complete_documents')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carriers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complete_documents', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('documents_complete')

    # ### end Alembic commands ###
