"""Initial tables

Revision ID: acbc6c8c1dc5
Revises: 
Create Date: 2025-11-11 21:34:50.067875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acbc6c8c1dc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.Enum('COMPANY', 'CARRIER', name='usertype'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('alternative_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('identity_document', sa.String(length=50), nullable=True),
    sa.Column('document_type', sa.Enum('CC', 'NIT', 'RUC', 'CE', name='documenttype'), nullable=True),
    sa.Column('document_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_date', sa.DateTime(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('account_status', sa.Enum('ACTIVE', 'PENDING_VERIFICATION', 'SUSPENDED', 'INACTIVE', name='accountstatus'), nullable=True),
    sa.Column('verification_level', sa.Enum('BASIC', 'VERIFIED', 'PREMIUM', name='verificationlevel'), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=True),
    sa.Column('lockout_date', sa.DateTime(), nullable=True),
    sa.Column('accepted_terms', sa.Boolean(), nullable=True),
    sa.Column('terms_acceptance_date', sa.DateTime(), nullable=True),
    sa.Column('notifications_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('identity_document')
    )
    op.create_table('carriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('carrier_type', sa.Enum('INDIVIDUAL', 'COMPANY', name='carriertype'), nullable=False),
    sa.Column('driver_license', sa.String(length=50), nullable=True),
    sa.Column('license_category', sa.String(length=10), nullable=True),
    sa.Column('license_expiry_date', sa.Date(), nullable=True),
    sa.Column('active_insurance', sa.Boolean(), nullable=True),
    sa.Column('insurance_policy', sa.String(length=100), nullable=True),
    sa.Column('insurance_expiry_date', sa.Date(), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('max_capacity_kg', sa.Float(), nullable=True),
    sa.Column('available_vehicle_types', sa.Text(), nullable=True),
    sa.Column('carrier_registration_date', sa.DateTime(), nullable=True),
    sa.Column('completed_trips', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('successful_delivery_rate', sa.Float(), nullable=True),
    sa.Column('document_status', sa.Enum('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='documentstatus'), nullable=True),
    sa.Column('complete_documents', sa.Boolean(), nullable=True),
    sa.Column('background_check_verified', sa.Boolean(), nullable=True),
    sa.Column('reliability_seal', sa.Boolean(), nullable=True),
    sa.Column('cargo_specializations', sa.Text(), nullable=True),
    sa.Column('usual_routes', sa.Text(), nullable=True),
    sa.Column('availability_24_7', sa.Boolean(), nullable=True),
    sa.Column('client_reference_1', sa.String(length=200), nullable=True),
    sa.Column('client_reference_2', sa.String(length=200), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_license'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('commercial_name', sa.String(length=200), nullable=True),
    sa.Column('incorporation_date', sa.Date(), nullable=True),
    sa.Column('company_type', sa.Enum('NATURAL', 'LEGAL', name='companytype'), nullable=False),
    sa.Column('company_size', sa.Enum('MICRO', 'SMALL', 'MEDIUM', 'LARGE', name='companysize'), nullable=True),
    sa.Column('annual_revenue', sa.Enum('LESS_100K', 'K100_500K', 'K500_1M', 'K1M_5M', 'MORE_5M', name='annualrevenue'), nullable=True),
    sa.Column('direct_employees', sa.Integer(), nullable=True),
    sa.Column('bank_reference', sa.String(length=100), nullable=True),
    sa.Column('commercial_reference_1', sa.String(length=200), nullable=True),
    sa.Column('commercial_reference_2', sa.String(length=200), nullable=True),
    sa.Column('commercial_reference_3', sa.String(length=200), nullable=True),
    sa.Column('has_environmental_license', sa.Boolean(), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('special_permits', sa.Text(), nullable=True),
    sa.Column('company_registration_date', sa.DateTime(), nullable=True),
    sa.Column('completed_shipments', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('legal_documentation_complete', sa.Boolean(), nullable=True),
    sa.Column('financial_verification', sa.Boolean(), nullable=True),
    sa.Column('trust_seal', sa.Boolean(), nullable=True),
    sa.Column('usual_cargo_types', sa.Text(), nullable=True),
    sa.Column('shipping_frequency', sa.Enum('OCCASIONAL', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'DAILY', name='shippingfrequency'), nullable=True),
    sa.Column('coverage_zones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    op.drop_table('carriers')
    op.drop_table('users')
    # ### end Alembic commands ###
